name: Updata

on:
  workflow_dispatch:

jobs:
  Updata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: 'V1.0'
          files: |
            soft/**/*
