name: Updata

on:
  workflow_dispatch:

jobs:
  Updata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # 👇 修复文件名：把冒号替换成 -
      - name: Fix invalid filenames
        run: |
          find . -name "*:*" -type f | while read f; do
            mv "$f" "${f//:/-}"
          done
          ls -la
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: 'V1.0'
          files: |
            soft/**/*
      - uses: actions/upload-artifact@v7
        with:
          name: my-artifact
          path: soft/dotnet/
